### ISSUE TITLE
Questions about zoomzoom functionality

### ISSUE THREAD

**Issue by richardsgf** [agileware/au.com.agileware.zoomzoom#1]
Hi,

I'm trying to understand some nuances about how zoomzoom works.  Can you help understand the following:

* Does zoomzoom require manually creating Zoom meetings and then providing the meeting ID in Civi?  Or does it create the meetings for you?
* Does zoomzoom support multiple Zoom accounts?
* Does zoomzoom import the private meeting join links for each participant so that they can be used in Scheduled Reminders from within Civi?  The [example schedule reminder](https://github.com/agileware/au.com.agileware.zoomzoom/blob/master/images/schedule-reminder-example.png) uses {zoom.join_url} which I'm guessing is a custom field on the event rather than the participant?
* How do you tell ZoomZoom which events are linked to a Zoom?  I looked in the code and it looks like it creates some custom event types.  Is it only those event types that get linked to a Zoom?  Can we define our own?
* Does ZoomZoom import participants that are unknown to Civi and create Civi records for them?
* If a Civi event is deleted, does ZoomZoom delete the corresponding meeting in Zoom?

Thank you for your help!

**Comment by agileware-justin** [comment]
> Does zoomzoom require manually creating Zoom meetings and then providing the meeting ID in Civi? Or does it create the meetings for you?

This extension is designed to be used with CiviRules. You use CiviRules to define the logic of when a Zoom should be created, updated, or deleted. Or if a Zoom Participant should be added or deleted.

These are the CiviRules actions that this extension provides.

![image](https://github.com/agileware/au.com.agileware.zoomzoom/assets/58866555/3746b40b-378a-41db-97dd-661cd4964af3)

> Does zoomzoom support multiple Zoom accounts?

Not currently. It could be modified to use multiple Zoom accounts if you need that feature.

> Does zoomzoom import the private meeting join links for each participant so that they can be used in Scheduled Reminders from within Civi? The [example schedule reminder](https://github.com/agileware/au.com.agileware.zoomzoom/blob/master/images/schedule-reminder-example.png) uses {zoom.join_url} which I'm guessing is a custom field on the event rather than the participant?

When you install the extension, two custom field groups are created as shown below.

![image](https://github.com/agileware/au.com.agileware.zoomzoom/assets/58866555/09b16f73-cae2-469a-8529-650b760655d6)

You can refer to both these groups of custom fields in the Scheduled Reminder. Note that the Zoom Registrant Join URL would be the "private meeting join link".

> How do you tell ZoomZoom which events are linked to a Zoom? I looked in the code and it looks like it creates some custom event types. Is it only those event types that get linked to a Zoom? Can we define our own?

Each CiviCRM Event which is linked to a Zoom Event has a CiviCRM Zoom ID set. The extension provides a CiviRule Condition to allow checking this criteria easier.

![image](https://github.com/agileware/au.com.agileware.zoomzoom/assets/58866555/557b1b90-bbd2-4f12-8340-0aa741962d1b)

> Does ZoomZoom import participants that are unknown to Civi and create Civi records for them?

Yes, see https://github.com/agileware/au.com.agileware.zoomzoom/blob/master/CRM/Zoomzoom/Zoom.php#L308

> If a Civi event is deleted, does ZoomZoom delete the corresponding meeting in Zoom?

Yes, you can set that up using a CiviRule.

**Comment by richardsgf** [comment]
This is so so helpful!  Thank you so much!

One last clarification:

_How do you tell ZoomZoom which events are linked to a Zoom? I looked in the code and it looks like it creates some custom event types. Is it only those event types that get linked to a Zoom? Can we define our own?

Each CiviCRM Event which is linked to a Zoom Event has a CiviCRM Zoom ID set. The extension provides a CiviRule Condition to allow checking this criteria easier._

So when I create an event, do I need to use your event types in order to trigger creation of a Zoom Event by zoomzoom?  Or can I use my own event types and somehow set a flag on the event to tell zoomzoom to create a corresponding event in Zoom?

Thank you so much

**Comment by agileware-justin** [comment]
You can use your own Event Types, it's all determined by the CiviRules you set up.

You set it up based on your requirements, that's how it all works.

**Comment by richardsgf** [comment]
Thank you so much for all of your kind explanations.  Really appreciate it.
