### ISSUE TITLE
Edits of message templates trigger Zoom creation

### ISSUE THREAD

**Issue by richardsgf** [agileware/au.com.agileware.zoomzoom#2]
If you have...
* An event type that should trigger Zoom integration (e.g. "Online Seminar via Zoom")
* An event template that is set with that event type

When you edit the event template, it will trigger the CiviRule to create the meeting or webinar on Zoom, and will populate that data into the event template.  

Further, it won't be possible to delete the zoom data out of the event template without disabling the zoomzoom CiviRules because the "Add Zoom to existing event" will evaluate that the zoom fields are empty and will fire, creating a new Zoom meeting and populating the data again in the event template.

The only way to resolve this is to disable the zoomzoom civirules before editing an event template that is of an event type which triggers zoomzoom, and then re-enable them when complete.

The root cause of this issue is that CiviRules do not appear to have a condition to identify if some action is taking place on an event template, so it isn't possible to exclude triggering on event templates.

**Comment by agileware-justin** [comment]
Thanks for reporting @richardsgf 

We are currently working on a project with Event Templates and Zoom integration. So very relevant. We'll test this and if we can reproduce, push out a fix.

**Comment by agileware-iris** [comment]
Hi @richardsgf!

I've just pushed out a fix. We never want to create a Zoom entity for event templates, so I've just put in a check to skip if the `is_template` flag is on.

Please install the 1.10.3 release to test and confirm if that fixes it for you. You shouldn't have to change any of your configuration.

**Comment by richardsgf** [comment]
Thank you so much!!  Confirming fixed.  Thank you again!!
